### ISSUE TITLE
[Bug]? LoadError on ledger_tools/csv2ledger when running csv2ledger

### ISSUE THREAD

**Issue by wakatara** [chrisnatali/ledger-tools#17]
git cloned the latest down and attempted your test run after a failed attempt or two at getting it to work from a simple `bundle install` in the root directory.

```bash
~/D/C/ledger-tools cat ./sample.csv | ./bin/csv2ledger                                                                                         
Traceback (most recent call last):
        2: from ./bin/csv2ledger:5:in `<main>'
        1: from /usr/local/Cellar/ruby/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:155:in `require'
/usr/local/Cellar/ruby/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:155:in `require': cannot load such file -- ledger_tools/csv2ledger (LoadError)
```
OSX 10.15.3, brew installed Ruby 2.7.0_0p0, fish shell 3.1.0

Kinda confused why this would be happening and also `require 'lib/ledger_tools/csv2ledger` not working. Ideas? Is this just a quirk of something I've done of the bundler install? 

lemme know. Could use some ideas. Googling was unfruitful. 

thanks!
Daryl.
(and also for maintaining such a ridonckulously useful utlilities!)

**Comment by wakatara** [comment]
Sidebar info: When I run this with bundler the '~>1.6' in the gemspec file I get an error that the dependencies cannot be resolved and that bundler is at 2.1.2 for the default gem. So, I had modified the gemspec file slightly to allow that and installs. Not sure if that is related or not, but bundler 1.6 is pretty agéd at this point so would assume not.  =]

**Comment by wakatara** [comment]
Embarassingly, cuz I thought I had done this, `bundle exec csv2ledger` does let the program run. However, I sadly hit another problem:

```
 ▲ ~/D/C/ledger-tools cat ./sample.csv | bundle exec ./bin/csv2ledger                                                                          9 changed files  master 
bundler: failed to load command: ./bin/csv2ledger (./bin/csv2ledger)
TypeError: no implicit conversion of nil into String
  /Users/daryl/Dropbox/Code/ledger-tools/lib/ledger_tools/csv2ledger.rb:131:in `strptime'
  /Users/daryl/Dropbox/Code/ledger-tools/lib/ledger_tools/csv2ledger.rb:131:in `date'
  /Users/daryl/Dropbox/Code/ledger-tools/lib/ledger_tools/csv2ledger.rb:107:in `record_to_transaction'
  /Users/daryl/Dropbox/Code/ledger-tools/lib/ledger_tools/csv2ledger.rb:73:in `block in csv_to_transactions'
  /usr/local/Cellar/ruby/2.7.0/lib/ruby/2.7.0/csv/parser.rb:1122:in `emit_row'
  /usr/local/Cellar/ruby/2.7.0/lib/ruby/2.7.0/csv/parser.rb:871:in `block in parse_quotable_loose'
  /usr/local/Cellar/ruby/2.7.0/lib/ruby/2.7.0/csv/parser.rb:52:in `block in each_line'
  /usr/local/Cellar/ruby/2.7.0/lib/ruby/2.7.0/csv/parser.rb:49:in `each_line'
  /usr/local/Cellar/ruby/2.7.0/lib/ruby/2.7.0/csv/parser.rb:49:in `each_line'
  /usr/local/Cellar/ruby/2.7.0/lib/ruby/2.7.0/csv/parser.rb:823:in `parse_quotable_loose'
  /usr/local/Cellar/ruby/2.7.0/lib/ruby/2.7.0/csv/parser.rb:336:in `parse'
  /usr/local/Cellar/ruby/2.7.0/lib/ruby/2.7.0/csv.rb:1280:in `each'
  /usr/local/Cellar/ruby/2.7.0/lib/ruby/2.7.0/csv.rb:1280:in `each'
  /Users/daryl/Dropbox/Code/ledger-tools/lib/ledger_tools/csv2ledger.rb:72:in `map'
  /Users/daryl/Dropbox/Code/ledger-tools/lib/ledger_tools/csv2ledger.rb:72:in `csv_to_transactions'
  /Users/daryl/Dropbox/Code/ledger-tools/lib/ledger_tools/csv2ledger.rb:81:in `write_csv_as_ledger'
  /Users/daryl/Dropbox/Code/ledger-tools/bin/csv2ledger:21:in `<top (required)>'
 ```

It appears that would be a problem due to a `nil` date field since strptime looks like the culprit but cannot find a problem with the inpur file. Ideas?

thanks!
Daryl.

**Comment by wakatara** [comment]
Closing with abject apologies. I either did not have enough coffee today or have just forgotten ruby having moved onto other languages. Sorry to bother you and thank you for maintaining this tool.   =]
